name: fi_intern_training
channels:
  - conda-forge
  - defaults
dependencies:
  - jupyterlab>=2.2.10
  - numpy>=1.21
  - pandas=1.0.5
  - matplotlib=3.2.2
  - xarray=0.15.1
  - netcdf4=1.5.3
  - dask=2.19.0
  - zarr=2.8.3
  - seaborn=0.11.2
  - cartopy=0.20.2
  - python=3.9.7
  - scikit-learn=1.0
  - statsmodels=0.13.0
  - s3fs=0.2.0
  - fsspec=2021.8.1
  - hvplot=0.7.3
  - wget=1.20.3
  - aiohttp=3.7.4.post0
  - geoviews=1.9.2
